name = "quare-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
CONTRACT_ADDRESS = ""
CHAIN_RPC_URL = ""
ALLOWED_ORIGINS = "*"
ADMIN_KEY = ""

[[kv_namespaces]]
binding = "RECORD_SECRETS"
id = ""
preview_id = ""
